project:
  name: {{ project_name }}
  version: "0.1.0"
  description: "Bot de Slack impulsado por IA para {{ project_name_title }}"
  author: "{{ project_name_title }} Team"
  license: "MIT"

bot:
  name: "Lucius"
  default_personality: "default"
  max_context_messages: 10
  context_expiry_minutes: 60

slack:
  socket_mode: true
  event_types:
    - message
    - app_mention
    - reaction_added

ai:
  provider: "groq"
  model: "llama3-70b-8192"
  max_tokens: 500
  temperature: 0.7
  top_p: 0.9

logging:
  level: "INFO"
  log_file: "logs/{{ project_name }}.log"
  max_log_size_mb: 10
  backup_count: 5

monitoring:
  enabled: true
  metrics:
    - response_time
    - token_usage
    - error_rate

security:
  token_validation: true
  rate_limiting:
    enabled: true
    max_requests_per_minute: 30

features:
  context_management: true
  personality_customization: true
  error_recovery: true

deployment:
  platform: "google_compute_engine"
  machine_type: "e2-micro"
  region: "us-central1"
  auto_restart: true

experimental:
  multimodal_support: false
  multilingual_support: false
